### ISSUE TITLE
Refresh Products build infrastructure

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Products#39]
Right now, Products app has a legacy configuration in TeamCity. 

It should have the same project structure and configuration as KitchenSink and Launcher. The build result should be presented in GitHub.

Part of: https://github.com/Starcounter/AdminTrack/issues/261

**Comment by KmaTTi89** [comment]
Done and waiting for TC update

**Comment by KmaTTi89** [comment]
Done
