### ISSUE TITLE
Change fields to properties in all database classes

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Products#51]
As requested in https://github.com/Starcounter/TechComm/issues/340, change fields to properties in all `[Database]` classes in this repo.

Scheduled after https://github.com/StarcounterApps/Simplified/issues/53

**Comment by Mihaiii** [comment]
Table `Cashier.Settings1 doesn't exists ([line](https://github.com/StarcounterApps/Cashier/blob/master/src/Cashier/Api/MainHandlers.cs#L97)).

**Comment by Mihaiii** [comment]
For test purposes, I would use a confirmation from anyone that `/products/settings` works as expected.

**Comment by warpech** [comment]
It works for me. You need SignIn app to authenticate and People app to create the organisation.

![bug](https://user-images.githubusercontent.com/566463/27740390-28c894a4-5db2-11e7-8098-dbf1c7cf97b5.gif)

**Comment by Mihaiii** [comment]
Close as done.
