### ISSUE TITLE
ProductTypesPage.html uses kitchensink prefixes in CSS

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Products#60]
### Steps to reproduce

Open /src/Products/wwwroot/Products/viewmodels/ProductTypesPage.html

### Expected result

CSS selectors should follow BEM with Products as prefix.
Preferably layouts should be done in Shadow DOM

### Actual result

Light DOM CSS contains `kitchensink` prefixes

##### Starcounter version 
n/a

##### Involved apps' version

 - StarcounterSamples/Products@3fc2fb25ace81b45d196eae4124f90ea53d08e62
 
##### Browsers affected
n/a
### Screenshot
n/a

**Comment by Mackiovello** [comment]
Fixed
